print("Maria Stephanie R. Pinon")
print("Kaganhao Santa Cruz, Marinduque")
print("March 03, 2001")
print("Marinduque State College, Boac Campus")
print("BS Information Technology")
print("Second Year - Section C")
print("Hobby1 - Watching Kdrama, Anime, En-o'clock and Cdrama")
print("Hobby2 - Stanning Kpop idols")
print("Hobby3 - Reading Wattpad and Webtoons")
print("Hobby4 - Sleeping")
print("Hobby5 - Gardening and Cooking")